import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getSession } from "@/lib/auth";
import LogoutButton from "@/components/LogoutButton";
import MobileNav from "@/components/layout/MobileNav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession()

  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {session ? (
          <div className="flex flex-col md:flex-row min-h-screen">
            <MobileNav isAdmin={session.role === 'ADMIN'} />
            <aside className="hidden md:flex w-64 bg-slate-900 text-white flex-col print:hidden shrink-0 sticky top-0 h-screen">
              <div className="p-4 border-b border-slate-700 flex justify-between items-center">
                <div>
                  <span className="font-bold text-xl block">ADM</span>
                  <span className="text-xs text-slate-400">Accommodation</span>
                </div>
              </div>
              <nav className="flex-1 p-4 space-y-2 flex flex-col overflow-visible gap-2">
                {session.role === 'ADMIN' && (
                  <>
                    <a href="/dashboard" className="block py-2 px-4 rounded hover:bg-slate-800 whitespace-nowrap">Dashboard</a>
                    <a href="/participants" className="block py-2 px-4 rounded hover:bg-slate-800 whitespace-nowrap">Participants</a>
                    <a href="/hotels" className="block py-2 px-4 rounded hover:bg-slate-800 whitespace-nowrap">Hotels</a>
                    <a href="/shads" className="block py-2 px-4 rounded hover:bg-slate-800 whitespace-nowrap">Shads</a>
                    <a href="/reports" className="block py-2 px-4 rounded hover:bg-slate-800 whitespace-nowrap">Reports</a>
                  </>
                )}
                <div className="pt-4 mt-4 border-t border-slate-700">
                  <a href="/volunteer" className="block py-2 px-4 rounded text-yellow-300 hover:bg-slate-800 font-bold whitespace-nowrap">Volunteer Ops</a>
                </div>
              </nav>
              <div className="p-4 border-t border-slate-700">
                <LogoutButton />
              </div>
            </aside>
            <main className="flex-1 bg-slate-50 min-h-screen w-full flex flex-col overflow-x-hidden">
              {session.role === 'ADMIN' && (
                <header className="bg-white border-b px-4 md:px-8 py-3 flex items-center justify-between print:hidden sticky top-0 z-20 shadow-sm">
                  <form action="/search" className="w-full max-w-2xl flex relative mx-auto md:mx-0">
                    <input 
                      type="text" 
                      name="q" 
                      placeholder="Global Search: Find any participant..." 
                      className="w-full border-2 border-slate-200 bg-slate-50 rounded-full px-6 py-2 text-sm focus:outline-none focus:border-blue-500 focus:bg-white transition-colors shadow-inner"
                      required
                    />
                    <button type="submit" className="absolute right-1.5 top-1.5 bg-blue-600 text-white px-4 py-1 rounded-full text-sm font-medium hover:bg-blue-700 shadow">Search</button>
                  </form>
                </header>
              )}
              <div className="flex-1">
                {children}
              </div>
            </main>
          </div>
        ) : (
          <main className="bg-slate-50 min-h-screen">
            {children}
          </main>
        )}
      </body>
    </html>
  );
}
